import jwt from 'jsonwebtoken';
import User from '../database/models/User';
import {Response} from 'express';
import fs from 'node:fs';

export interface ITokenPayload {
    userID: string,
    name: string,
    email: string
}

const createToken = (user: User) => {
    const payload: ITokenPayload = {
        userID: user.id,
        name: user.name,
        email: user.email
    };
    return jwt.sign(
        payload,
        process.env.JWT_SECRET as string,
        {expiresIn: process.env.JWT_LIFETIME as string}
    );
}

const createCookieWithToken = (res: Response, token: string) => {
    const oneDay = 1000 * 60 * 60 * 24;
    res.cookie('token', token, {
        httpOnly: true,
        expires: new Date(Date.now() + oneDay),
        secure: process.env.NODE_ENV === 'production',
        signed: true
    });
}

const verifyToken = (token: string) => {
    return (jwt.verify(token, process.env.JWT_SECRET as string) as ITokenPayload);
}

const deleteImage = async(path: string) => {
    await fs.unlink(path, (err) => {
        if (err) {
            console.log(err);
        }
    });
}

const countries = [
    "Afghanistan",
    "Albania",
    "Algeria",
    "Andorra",
    "Angola",
    "Antigua & Deps",
    "Argentina",
    "Armenia",
    "Australia",
    "Austria",
    "Azerbaijan",
    "Bahamas",
    "Bahrain",
    "Bangladesh",
    "Barbados",
    "Belarus",
    "Belgium",
    "Belize",
    "Benin",
    "Bhutan",
    "Bolivia",
    "Bosnia Herzegovina",
    "Botswana",
    "Brazil",
    "Brunei",
    "Bulgaria",
    "Burkina",
    "Burundi",
    "Cambodia",
    "Cameroon",
    "Canada",
    "Cape Verde",
    "Central African Rep",
    "Chad",
    "Chile",
    "China",
    "Colombia",
    "Comoros",
    "Congo",
    "Congo {Democratic Rep}",
    "Costa Rica",
    "Croatia",
    "Cuba",
    "Cyprus",
    "Czech Republic",
    "Denmark",
    "Djibouti",
    "Dominica",
    "Dominican Republic",
    "East Timor",
    "Ecuador",
    "Egypt",
    "El Salvador",
    "Equatorial Guinea",
    "Eritrea",
    "Estonia",
    "Ethiopia",
    "Fiji",
    "Finland",
    "France",
    "Gabon",
    "Gambia",
    "Georgia",
    "Germany",
    "Ghana",
    "Greece",
    "Grenada",
    "Guatemala",
    "Guinea",
    "Guinea-Bissau",
    "Guyana",
    "Haiti",
    "Honduras",
    "Hungary",
    "Iceland",
    "India",
    "Indonesia",
    "Iran",
    "Iraq",
    "Ireland {Republic}",
    "Israel",
    "Italy",
    "Ivory Coast",
    "Jamaica",
    "Japan",
    "Jordan",
    "Kazakhstan",
    "Kenya",
    "Kiribati",
    "Korea North",
    "Korea South",
    "Kosovo",
    "Kuwait",
    "Kyrgyzstan",
    "Laos",
    "Latvia",
    "Lebanon",
    "Lesotho",
    "Liberia",
    "Libya",
    "Liechtenstein",
    "Lithuania",
    "Luxembourg",
    "Macedonia",
    "Madagascar",
    "Malawi",
    "Malaysia",
    "Maldives",
    "Mali",
    "Malta",
    "Marshall Islands",
    "Mauritania",
    "Mauritius",
    "Mexico",
    "Micronesia",
    "Moldova",
    "Monaco",
    "Mongolia",
    "Montenegro",
    "Morocco",
    "Mozambique",
    "Myanmar, {Burma}",
    "Namibia",
    "Nauru",
    "Nepal",
    "Netherlands",
    "New Zealand",
    "Nicaragua",
    "Niger",
    "Nigeria",
    "Norway",
    "Oman",
    "Pakistan",
    "Palau",
    "Panama",
    "Papua New Guinea",
    "Paraguay",
    "Peru",
    "Philippines",
    "Poland",
    "Portugal",
    "Qatar",
    "Romania",
    "Russian Federation",
    "Rwanda",
    "St Kitts & Nevis",
    "St Lucia",
    "Saint Vincent & the Grenadines",
    "Samoa",
    "San Marino",
    "Sao Tome & Principe",
    "Saudi Arabia",
    "Senegal",
    "Serbia",
    "Seychelles",
    "Sierra Leone",
    "Singapore",
    "Slovakia",
    "Slovenia",
    "Solomon Islands",
    "Somalia",
    "South Africa",
    "South Sudan",
    "Spain",
    "Sri Lanka",
    "Sudan",
    "Suriname",
    "Swaziland",
    "Sweden",
    "Switzerland",
    "Syria",
    "Taiwan",
    "Tajikistan",
    "Tanzania",
    "Thailand",
    "Togo",
    "Tonga",
    "Trinidad & Tobago",
    "Tunisia",
    "Turkey",
    "Turkmenistan",
    "Tuvalu",
    "Uganda",
    "Ukraine",
    "United Arab Emirates",
    "United Kingdom",
    "United States",
    "Uruguay",
    "Uzbekistan",
    "Vanuatu",
    "Vatican City",
    "Venezuela",
    "Vietnam",
    "Yemen",
    "Zambia",
    "Zimbabwe"
];

const isValidCountry = (countryName: string) => {
    return countries.includes(countryName);
}

const hobbies = [
    "Reading",
    "Painting",
    "Gardening",
    "Cooking",
    "Playing guitar",
    "Writing",
    "Hiking",
    "Photography",
    "Knitting",
    "Drawing",
    "Sculpting",
    "Playing video games",
    "Skiing",
    "Dancing",
    "Fishing",
    "Bird watching",
    "Yoga",
    "Meditation",
    "Singing",
    "Woodworking",
    "Pottery",
    "Camping",
    "Traveling",
    "Running",
    "Swimming",
    "Cycling",
    "Mountain climbing",
    "Surfing",
    "Sailing",
    "Scuba diving",
    "Skydiving",
    "Bungee jumping",
    "Canoeing",
    "Kayaking",
    "Rock climbing",
    "Ice skating",
    "Snowboarding",
    "Archery",
    "Baking",
    "Calligraphy",
    "Chess",
    "Collecting stamps",
    "Collecting coins",
    "Collecting antiques",
    "DIY projects",
    "Metal detecting",
    "Learning languages",
    "Playing chess",
    "Playing cards",
    "Pottery",
    "Sudoku",
    "Whittling",
    "Astrology",
    "Golfing",
    "Juggling",
    "Magic tricks",
    "Parkour",
    "RC vehicles",
    "Origami",
    "Puzzles",
    "Quilting",
    "Robotics",
    "Scrapbooking",
    "Soap making",
    "Stargazing",
    "Tie-dyeing",
    "Ukulele",
    "Urban exploration",
    "Vintage cars",
    "Volunteering",
    "Wine tasting",
    "Wood carving",
    "Ziplining",
    "Zumba",
    "Board games",
    "Bowling",
    "Car restoration",
    "Calligraphy",
    "Candle making",
    "Canyoning",
    "Caving",
    "Falconry",
    "Foraging",
    "Geocaching",
    "Glassblowing",
    "Horseback riding",
    "Kite flying",
    "Metalworking",
    "Needlepoint",
    "Orienteering",
    "Paintball",
    "Paragliding",
    "Parasailing",
    "Pearl diving",
    "Puppetry",
    "Rappelling",
    "Reflexology",
    "Sand art",
    "Tai chi",
    "Welding",
    "Windsurfing",
    "Wood burning",
    "Zorbing",
    "Acting",
    "Antiquing",
    "Aquarium keeping",
    "Astrophotography",
    "Backpacking",
    "Ballet",
    "Barbecueing",
    "Basket weaving",
    "Beachcombing",
    "Beer brewing",
    "Bird keeping",
    "Blacksmithing",
    "Bodybuilding",
    "Bookbinding",
    "Cake decorating",
    "Cardistry",
    "Cartooning",
    "Ceramics",
    "Coding",
    "Coin collecting",
    "Coloring",
    "Computer programming",
    "Conworlding",
    "Cosplaying",
    "Couponing",
    "Creative writing",
    "Crocheting",
    "Crossword puzzles",
    "Cryptography",
    "Curling",
    "Cycling",
    "Darts",
    "Digital art",
    "Disc golf",
    "Dominoes",
    "Dowsing",
    "Drama",
    "Electronics",
    "Embroidery",
    "Entomology",
    "Falconry",
    "Fashion design",
    "Fire dancing",
    "Flower arranging",
    "Fly fishing",
    "Fly tying",
    "Food preservation",
    "Genealogy",
    "Glass art",
    "Graffiti",
    "Gunsmithing",
    "Horse riding",
    "Hot air ballooning",
    "Hydroponics",
    "Ice fishing",
    "Jamming",
    "Jewelry making",
    "Jigsaw puzzles",
    "Journaling",
    "Jump roping",
    "Kendama",
    "Knife making",
    "Lapidary",
    "Leather crafting",
    "Lock picking",
    "Mahjong",
    "Makeup",
    "Marble collecting",
    "Martial arts",
    "Metal detecting",
    "Model building",
    "Model railroading",
    "Motorcycling",
    "Musical instruments",
    "Origami",
    "Paintball",
    "Paragliding",
    "Poker",
    "Radio-controlled model",
    "Reading",
    "Remote control vehicles",
    "Robot combat",
    "Role-playing games",
    "Scouting",
    "Sculpture",
    "Sewing",
    "Shoemaking",
    "Slot car racing",
    "Stone carving",
    "Surf fishing",
    "Table football",
    "Table tennis",
    "Taxidermy",
    "Tea tasting",
    "Thrifting",
    "Topiary",
    "Toy collecting",
    "Tutoring",
    "Ultimate frisbee",
    "Upcycling",
    "Videography",
    "Virtual reality",
    "Walking",
    "Watching movies",
    "Watching television",
    "Water skiing",
    "Weightlifting",
    "Whale watching",
    "Whittling",
    "Wine making",
    "Woodworking",
    "Worldbuilding",
    "Yo-yoing",
    "Zumba"
];

const isValidHobby = (hobbyName: string) => {
    return hobbies.includes(hobbyName);
}

export {
    createToken,
    createCookieWithToken,
    verifyToken,
    deleteImage,
    isValidCountry,
    isValidHobby
};